#ifndef CBOR_H_
#define CBOR_H_

#ifdef HAVE_PRAGMA_ONCE
#pragma once
#endif

#define CBOR_MAJOR_TYPE_UNSIGNED_INTEGER 0x00
#define CBOR_MAJOR_TYPE_NEGATIVE_INTEGER 0x20
#define CBOR_MAJOR_TYPE_BYTE_STRING 0x40
#define CBOR_MAJOR_TYPE_TEXT_STRING 0x60
#define CBOR_MAJOR_TYPE_ARRAY 0x80
#define CBOR_MAJOR_TYPE_MAP 0xA0
#define CBOR_MAJOR_TYPE_TAG 0xC0
#define CBOR_MAJOR_TYPE_SIMPLE_VALUE 0xE0

#define CBOR_ADDITIONAL_INFO_UINT8 0x18
#define CBOR_ADDITIONAL_INFO_UINT16 0x19
#define CBOR_ADDITIONAL_INFO_UINT32 0x1A
#define CBOR_ADDITIONAL_INFO_UINT64 0x1B
#define CBOR_ADDITIONAL_INFO_INFINITE 0x1F

#define CBOR_SIMPLE_VALUE_TRUE (CBOR_MAJOR_TYPE_SIMPLE_VALUE | 0x15)
#define CBOR_SIMPLE_VALUE_FALSE (CBOR_MAJOR_TYPE_SIMPLE_VALUE | 0x14)
#define CBOR_SIMPLE_VALUE_NULL (CBOR_MAJOR_TYPE_SIMPLE_VALUE | 0x16)
#define CBOR_SIMPLE_VALUE_UNDEFINED (CBOR_MAJOR_TYPE_SIMPLE_VALUE | 0x17)

#define CBOR_BREAK 0xFF

#define Cbor_GetMejorType(octet) (octet & 0xE0)
#define Cbor_GetAdditionalInfo(octet) (octet & 0x1F)

#endif // CBOR_H_
